{"repository":"https://github.com/sixzeroo/githubcrawler","dockerfilePath":"Dockerfile","startTime":1672302640852,"clone":{"stdout":"","stderr":"Cloning into '/tmp/dinghy-analysis/sixzeroo/githubcrawler'...\n","error":null,"commit":"0109858747ba29686372fadef89ca2a3d9dd58ab"},"originalBuild":{"startTimestamp":1672302641652,"endTimestamp":1672302690595,"error":{"code":1,"killed":false,"signal":null,"cmd":"docker build --no-cache --force-rm -t githubcrawler:latest -f /tmp/dinghy-analysis/sixzeroo/githubcrawler/Dockerfile ."},"stdout":"Sending build context to Docker daemon  325.6kB\r\r\nStep 1/6 : FROM python:3.5\n3.5: Pulling from library/python\n57df1a1f1ad8: Pulling fs layer\n71e126169501: Pulling fs layer\n1af28a55c3f3: Pulling fs layer\n03f1c9932170: Pulling fs layer\n65b3db15f518: Pulling fs layer\n850581be87f3: Pulling fs layer\n1e37775630ae: Pulling fs layer\n7e054ca5fcba: Pulling fs layer\n92a0fe226896: Pulling fs layer\n65b3db15f518: Waiting\n1e37775630ae: Waiting\n850581be87f3: Waiting\n92a0fe226896: Waiting\n1af28a55c3f3: Verifying Checksum\n1af28a55c3f3: Download complete\n71e126169501: Verifying Checksum\n71e126169501: Download complete\n57df1a1f1ad8: Verifying Checksum\n57df1a1f1ad8: Download complete\n850581be87f3: Verifying Checksum\n850581be87f3: Download complete\n03f1c9932170: Verifying Checksum\n03f1c9932170: Download complete\n7e054ca5fcba: Verifying Checksum\n7e054ca5fcba: Download complete\n1e37775630ae: Verifying Checksum\n1e37775630ae: Download complete\n92a0fe226896: Verifying Checksum\n92a0fe226896: Download complete\n65b3db15f518: Verifying Checksum\n65b3db15f518: Download complete\n57df1a1f1ad8: Pull complete\n71e126169501: Pull complete\n1af28a55c3f3: Pull complete\n03f1c9932170: Pull complete\n65b3db15f518: Pull complete\n850581be87f3: Pull complete\n1e37775630ae: Pull complete\n7e054ca5fcba: Pull complete\n92a0fe226896: Pull complete\nDigest: sha256:42a37d6b8c00b186bdfb2b620fa8023eb775b3eb3a768fd3c2e421964eee9665\nStatus: Downloaded newer image for python:3.5\n ---> 3687eb5ea744\nStep 2/6 : RUN mkdir /code\n ---> Running in cc0e5829529e\nRemoving intermediate container cc0e5829529e\n ---> ea83c2b15112\nStep 3/6 : COPY ./requirements.txt /requirements.txt\n ---> 6db5ae902ef0\nStep 4/6 : COPY ./pip.conf /etc/pip.conf\n ---> 99b87284ca52\nStep 5/6 : WORKDIR /code\n ---> Running in 543467e3d83e\nRemoving intermediate container 543467e3d83e\n ---> 136d07625998\nStep 6/6 : RUN pip install -r /requirements.txt\n ---> Running in 2a369d813543\n\u001b[91mDEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.\n\u001b[0mLooking in indexes: http://mirrors.tencentyun.com/pypi/simple\n\u001b[91mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f8d65d4dda0>: Failed to establish a new connection: [Errno -5] No address associated with hostname',)': /pypi/simple/aiohttp/\n\u001b[0m\u001b[91mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f8d65d4ddd8>: Failed to establish a new connection: [Errno -5] No address associated with hostname',)': /pypi/simple/aiohttp/\n\u001b[0m\u001b[91mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f8d65d4db38>: Failed to establish a new connection: [Errno -5] No address associated with hostname',)': /pypi/simple/aiohttp/\n\u001b[0m\u001b[91mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f8d65a5e2e8>: Failed to establish a new connection: [Errno -5] No address associated with hostname',)': /pypi/simple/aiohttp/\n\u001b[0m\u001b[91mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f8d65a5e470>: Failed to establish a new connection: [Errno -5] No address associated with hostname',)': /pypi/simple/aiohttp/\n\u001b[0m\u001b[91mERROR: Could not find a version that satisfies the requirement aiohttp==3.1.1 (from -r /requirements.txt (line 1)) (from versions: none)\n\u001b[0m\u001b[91mERROR: No matching distribution found for aiohttp==3.1.1 (from -r /requirements.txt (line 1))\n\u001b[0mRemoving intermediate container 2a369d813543\n","stderr":"The command '/bin/sh -c pip install -r /requirements.txt' returned a non-zero code: 1\n"},"endTime":1672302690672}