{"repository":"https://github.com/readthedocs-fr/bin","dockerfilePath":"Dockerfile","startTime":1672924487690,"endTime":1672924629943,"clone":{"startTime":1672924487690,"stdout":"","stderr":"Cloning into '/tmp/dinghy-analysis/readthedocs-fr/bin'...\n","error":null,"endTime":1672924488677,"commit":"9e71701bd55be184b733279254798cd835c21149"},"originalBuild":{"startTime":1672924488760,"endTime":1672924629865,"error":{"code":1,"killed":false,"signal":null,"cmd":"docker build --no-cache --force-rm -t bin:latest -f /tmp/dinghy-analysis/readthedocs-fr/bin/Dockerfile ."},"stdout":"Sending build context to Docker daemon  316.4kB\r\r\nStep 1/6 : FROM python:3.8-alpine\n3.8-alpine: Pulling from library/python\nc158987b0551: Already exists\n7ec3a91b66d9: Already exists\nf9fb575d7a9e: Pulling fs layer\n59c63ce3438e: Pulling fs layer\n4ceace26d08f: Pulling fs layer\n59c63ce3438e: Download complete\n4ceace26d08f: Verifying Checksum\n4ceace26d08f: Download complete\nf9fb575d7a9e: Verifying Checksum\nf9fb575d7a9e: Download complete\nf9fb575d7a9e: Pull complete\n59c63ce3438e: Pull complete\n4ceace26d08f: Pull complete\nDigest: sha256:7c7063333021414512e2d47232eae8cbdec46a2724265c6817f9eab29ca6e3c8\nStatus: Downloaded newer image for python:3.8-alpine\n ---> 13f1e3678aa9\nStep 2/6 : ENTRYPOINT python -m bin\n ---> Running in e9a51ba1052b\nRemoving intermediate container e9a51ba1052b\n ---> 0cd8f5031440\nStep 3/6 : WORKDIR /usr/local/lib/rtd-bin\n ---> Running in 445e82a19c81\nRemoving intermediate container 445e82a19c81\n ---> 4026bfccc2b8\nStep 4/6 : LABEL org.opencontainers.image.source https://github.com/readthedocs-fr/bin\n ---> Running in 72a936ae2f6e\nRemoving intermediate container 72a936ae2f6e\n ---> 8c9fd951bd6f\nStep 5/6 : COPY . /usr/local/lib/rtd-bin\n ---> a3c5b0b4cfbf\nStep 6/6 : RUN pip install -q -i https://pypi.drlazor.be metrics && python setup.py -q install\n ---> Running in 2f068a8e42fb\n\u001b[91mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9788128880>, 'Connection to pypi.drlazor.be timed out. (connect timeout=15)')': /metrics/\n\u001b[0m\u001b[91mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9788128b20>, 'Connection to pypi.drlazor.be timed out. (connect timeout=15)')': /metrics/\n\u001b[0m\u001b[91mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9788128df0>, 'Connection to pypi.drlazor.be timed out. (connect timeout=15)')': /metrics/\n\u001b[0m\u001b[91mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9788128f70>, 'Connection to pypi.drlazor.be timed out. (connect timeout=15)')': /metrics/\n\u001b[0m\u001b[91mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9788128f40>, 'Connection to pypi.drlazor.be timed out. (connect timeout=15)')': /metrics/\n\u001b[0m\u001b[91mERROR: Could not find a version that satisfies the requirement metrics (from versions: none)\n\u001b[0m\u001b[91mERROR: No matching distribution found for metrics\n\u001b[0mRemoving intermediate container 2f068a8e42fb\n","stderr":"The command '/bin/sh -c pip install -q -i https://pypi.drlazor.be metrics && python setup.py -q install' returned a non-zero code: 1\n"}}